# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Tom\Dropbox\Projects\YoutubeMirrorTool\YoutubeMirrorClientMain.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1433, 870)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:/Images/0e9.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        self.pushButtonAdd.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.pushButtonAdd.setFont(font)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_9.addWidget(self.pushButtonAdd)
        self.pushButtonMinus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMinus.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonMinus.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.pushButtonMinus.setFont(font)
        self.pushButtonMinus.setObjectName("pushButtonMinus")
        self.horizontalLayout_9.addWidget(self.pushButtonMinus)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem1 = QtWidgets.QSpacerItem(77, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.toolButtonRefresh = QtWidgets.QToolButton(self.centralwidget)
        self.toolButtonRefresh.setEnabled(True)
        self.toolButtonRefresh.setMinimumSize(QtCore.QSize(50, 42))
        self.toolButtonRefresh.setMaximumSize(QtCore.QSize(999999, 9999999))
        self.toolButtonRefresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Pictures/syncicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRefresh.setIcon(icon1)
        self.toolButtonRefresh.setObjectName("toolButtonRefresh")
        self.horizontalLayout_7.addWidget(self.toolButtonRefresh)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidgetChannels = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetChannels.sizePolicy().hasHeightForWidth())
        self.tableWidgetChannels.setSizePolicy(sizePolicy)
        self.tableWidgetChannels.setMinimumSize(QtCore.QSize(323, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tableWidgetChannels.setFont(font)
        self.tableWidgetChannels.setObjectName("tableWidgetChannels")
        self.tableWidgetChannels.setColumnCount(0)
        self.tableWidgetChannels.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidgetChannels)
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.mainVideoContainer = QtWidgets.QVBoxLayout()
        self.mainVideoContainer.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.mainVideoContainer.setSpacing(3)
        self.mainVideoContainer.setObjectName("mainVideoContainer")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidgetVideos = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tableWidgetVideos.sizePolicy().hasHeightForWidth())
        self.tableWidgetVideos.setSizePolicy(sizePolicy)
        self.tableWidgetVideos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetVideos.setDragEnabled(True)
        self.tableWidgetVideos.setObjectName("tableWidgetVideos")
        self.tableWidgetVideos.setColumnCount(0)
        self.tableWidgetVideos.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetVideos, 0, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 4)
        self.mainVideoContainer.addLayout(self.gridLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btnResizeUp = QtWidgets.QToolButton(self.centralwidget)
        self.btnResizeUp.setObjectName("btnResizeUp")
        self.horizontalLayout_3.addWidget(self.btnResizeUp)
        self.btnResizeDown = QtWidgets.QToolButton(self.centralwidget)
        self.btnResizeDown.setObjectName("btnResizeDown")
        self.horizontalLayout_3.addWidget(self.btnResizeDown)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.mainVideoContainer.addLayout(self.horizontalLayout_3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(368, 252))
        self.groupBox.setObjectName("groupBox")
        self.txtName = QtWidgets.QLineEdit(self.groupBox)
        self.txtName.setGeometry(QtCore.QRect(110, 23, 251, 20))
        self.txtName.setObjectName("txtName")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 23, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 48, 91, 16))
        self.label_4.setObjectName("label_4")
        self.txtDesc = QtWidgets.QTextEdit(self.groupBox)
        self.txtDesc.setGeometry(QtCore.QRect(110, 53, 251, 81))
        self.txtDesc.setReadOnly(True)
        self.txtDesc.setObjectName("txtDesc")
        self.txtUploadDate = QtWidgets.QLineEdit(self.groupBox)
        self.txtUploadDate.setGeometry(QtCore.QRect(110, 143, 251, 20))
        self.txtUploadDate.setObjectName("txtUploadDate")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 143, 81, 16))
        self.label_5.setObjectName("label_5")
        self.txtDownloadDate = QtWidgets.QLineEdit(self.groupBox)
        self.txtDownloadDate.setGeometry(QtCore.QRect(110, 168, 251, 20))
        self.txtDownloadDate.setObjectName("txtDownloadDate")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 169, 81, 16))
        self.label_6.setObjectName("label_6")
        self.txtLLocalLocation = QtWidgets.QLineEdit(self.groupBox)
        self.txtLLocalLocation.setGeometry(QtCore.QRect(110, 194, 251, 20))
        self.txtLLocalLocation.setObjectName("txtLLocalLocation")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 194, 81, 16))
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_6.setRowStretch(0, 1)
        self.mainVideoContainer.addLayout(self.gridLayout_6)
        self.horizontalLayout.addLayout(self.mainVideoContainer)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1433, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuVie = QtWidgets.QMenu(self.menubar)
        self.menuVie.setObjectName("menuVie")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuVie.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonAdd, self.pushButtonMinus)
        MainWindow.setTabOrder(self.pushButtonMinus, self.toolButtonRefresh)
        MainWindow.setTabOrder(self.toolButtonRefresh, self.tableWidgetChannels)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Channels"))
        self.pushButtonAdd.setText(_translate("MainWindow", "+"))
        self.pushButtonMinus.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "Videos"))
        self.tableWidgetVideos.setSortingEnabled(True)
        self.btnResizeUp.setText(_translate("MainWindow", "6"))
        self.btnResizeDown.setText(_translate("MainWindow", "..."))
        self.groupBox.setTitle(_translate("MainWindow", "Video Data"))
        self.label_3.setText(_translate("MainWindow", "Video Name:"))
        self.label_4.setText(_translate("MainWindow", "Video Description:"))
        self.label_5.setText(_translate("MainWindow", "Upload Date:"))
        self.label_6.setText(_translate("MainWindow", "Download Date:"))
        self.label_7.setText(_translate("MainWindow", "Local Location:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuVie.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

